###################### Filebeat Configuration Example For Modsecurity#########################

# This file is an example configuration file highlighting settings for Modsecurity logs
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/log/modsec_audit.log

  # type
  document_type: mod_security

  # The regexp Pattern that has to be matched. The example pattern matches all lines starting with [
  multiline.pattern: ^--[a-fA-F0-9]{8}-Z--$

  # Defines if the pattern set under pattern should be negated or not. Default is false.
  multiline.negate: true

  # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
  multiline.match: before

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]
